hieradata/trd/base.yaml

Create separate base file for location trd

---

.gitignore
Vagrantfile

Allows the use of the environment variable HIMLAR_CERTNAME to change certname
in Puppet

Himlar envvars

---

Puppetfile
hieradata/bgo/common.yaml
hieradata/defaults/foreman.yaml

Initial foreman configuration: Necessary puppet modules for The Foreman and a postgres database plus hieradata.

Initial foreman configuration

---

Puppetfile
hieradata/defaults/foreman.yaml

Foreman fixes

---

Vagrantfile
provision/bootstrap.sh
provision/puppetmodules.sh
provision/puppetrun.sh

Changed so that modules provisioning is a separate script

Provisioning improvements

---

hieradata/defaults/foreman.yaml

without merge remote branch this time around

Added config data for discovery images and added template plugin

---

Puppetfile
Vagrantfile
hieradata/bgo/common.yaml
hieradata/bgo/foreman.yaml
provision/bgo_foreman.sh
provision/bootstrap.sh

A new module and som provisioning.

Added support for managing network interfaces with puppet and netcf

---

hieradata/defaults/foreman.yaml
hieradata/nodes/osl-foreman-bootstrap.vagrant.local.yaml
hieradata/osl/foreman.yaml

First data set for osl-based Foreman installs

Osl foreman data

---

Puppetfile
hieradata/defaults/libvirt.yaml

Including a default libvirt config through hieradata defaults

Adding libvirt role

---

Puppetfile
Vagrantfile
hieradata/bgo/foreman.yaml
hieradata/defaults/common.yaml
hieradata/defaults/foreman.yaml
hieradata/vagrant/foreman.yaml
provision/foreman-pxe-setup.sh

Better working vagrant data for Foreman role
* DNS server enabled, upstream DNS fwd to 8.8.8.8
* Puppetmaster disabled for now, first puppet.conf settings in common.yaml

Foreman vagrant data

---

Vagrantfile
provision/bootstrap.sh
provision/puppetmodules.sh
provision/puppetrun.sh

Now Puppet will run boostrap runs first, then another run. This will
simulate how we'll need to provision physical nodes too as e.g network
interfaces will need to be configured before facter can find values
for them (and use those in application configs)

Improved provisioning

---

hieradata/defaults/foreman.yaml

For some reason we got it all wrong in the end. Now it will become right, though.

Removed redundant setting and selected the correct ipmi driver

---

hieradata/defaults/login.yaml

These whitespaces prevented puppet to apply

Removed whitespaces in ssh keys

---

Puppetfile
Vagrantfile
hieradata/bgo/common.yaml
hieradata/bgo/login.yaml
hieradata/defaults/common.yaml
hieradata/defaults/foreman.yaml
hieradata/defaults/login.yaml
hieradata/nodes/vagrant-login-1.himlar.local.yaml
hieradata/osl/common.yaml
hieradata/osl/login.yaml
hieradata/trd/common.yaml
hieradata/trd/login.yaml
hieradata/vagrant/common.yaml
hieradata/vagrant/foreman.yaml
hieradata/vagrant/login.yaml
provision/bootstrap-controller.sh
provision/bootstrap-foreman.sh
provision/foreman-vagrant-setup.sh
provision/foreman-vagrant-up.sh
provision/puppetbootstrap.sh
provision/puppetrun.sh

DHCP management using common data hash

---

provision/foreman-bgo-setup.sh
provision/foreman-osl-setup.sh
provision/foreman-trd-setup.sh
provision/foreman-vagrant-setup.sh

* Use foreman templates plugin to import templates
* Updated partitioning logic by pulling in newer tag of norcams/community-templates
* New default public password with no dash in it :+1:

Rake import templates

---

provision/foreman-osl-setup.sh

Improved logic for creatnig domains and subnets at osl
(to be reused in the other scripts)

Consistently adding domains and subnets

---

provision/foreman-bgo-setup.sh
provision/foreman-osl-setup.sh
provision/foreman-trd-setup.sh
provision/foreman-vagrant-setup.sh

Updated and aligned foreman settings scripts with changes from working with osl

Foreman scripts update

---

Puppetfile
hieradata/common/common.yaml
hieradata/common/roles/controller.yaml
hieradata/common/roles/foreman.yaml
hieradata/common/roles/libvirt.yaml
hieradata/common/roles/login.yaml

* Do not manage firewall for login (yet!)
* Enable ports for foreman profile
* Enable ports for libvirt profile
See https://github.com/norcams/puppeels/commit/d8afc419ffea30101051211cfbd8bf060c4230b9

Firewall management

---

Puppetfile
hieradata/bgo/common.yaml
hieradata/common/common.yaml
hieradata/common/roles/foreman.yaml
hieradata/osl/common.yaml
hieradata/trd/common.yaml
hieradata/vagrant/common.yaml

* Expanded the profile to manage dns using nsupdate
* Added data hashes that registers A and CNAME records

Updated profile with dns management

---

hieradata/osl/roles/login.yaml

Special repo management for osl-login-1 as a Redhat machine

---

hieradata/trd/roles/login.yaml

Trd rhelrepo

---

hieradata/bgo/common.yaml
hieradata/bgo/modules/glance.yaml
hieradata/bgo/modules/keystone.yaml
hieradata/bgo/modules/neutron.yaml
hieradata/bgo/modules/nova.yaml
hieradata/common/common.yaml
hieradata/common/modules/cinder.yaml
hieradata/common/modules/glance.yaml
hieradata/common/modules/keystone.yaml
hieradata/common/modules/neutron.yaml
hieradata/common/modules/nova.yaml
hieradata/common/modules/profile.yaml
hieradata/common/roles/master.yaml
hieradata/dev01/common.yaml
hieradata/dev01/modules/glance.yaml
hieradata/dev01/modules/keystone.yaml
hieradata/dev01/modules/neutron.yaml
hieradata/dev01/modules/nova.yaml
hieradata/osl/common.yaml
hieradata/osl/modules/glance.yaml
hieradata/osl/modules/keystone.yaml
hieradata/osl/modules/neutron.yaml
hieradata/osl/modules/nova.yaml
hieradata/trd/common.yaml
hieradata/trd/modules/glance.yaml
hieradata/trd/modules/keystone.yaml
hieradata/trd/modules/neutron.yaml
hieradata/trd/modules/nova.yaml

Basic configuration of the OpenStack cinder service

Cinderservice

---

Puppetfile
hieradata/common/common.yaml
hieradata/common/modules/ceph.yaml
hieradata/common/modules/cinder.yaml
hieradata/common/modules/glance.yaml
hieradata/common/modules/nova.yaml
hieradata/common/roles/cephmon.yaml
hieradata/common/roles/compute.yaml
hieradata/common/roles/storage.yaml
tests/01-keystone-create_demo_user.sh
tests/02-glance-import_centos_image.sh
tests/02-glance-import_cirros_image.sh
tests/06-nova-boot_centos.sh
tests/06-nova-boot_cirros.sh

This is a working OpenStack cinder and glance with Ceph configuration.

OpenStack Cinder, Glance and Nova working with Ceph

---

Puppetfile
hieradata/vagrant/modules/cinder.yaml
hieradata/vagrant/modules/elasticsearch.yaml
hieradata/vagrant/modules/logstash.yaml
hieradata/vagrant/modules/rsyslog.yaml
hieradata/vagrant/roles/logger.yaml
profile/manifests/logging/elasticsearch.pp
profile/manifests/logging/logstash.pp
profile/templates/logging/logstash/elasticsearch-template.json
profile/templates/logging/logstash/openstack.conf.erb
profile/templates/logging/logstash/patterns.erb
profile/templates/logging/rsyslog/server.conf.erb

Lettest å teste med å kjøre alt opp å så se om man får data i elasticsearch via Kibana:
- installer Kibana fra https://www.elastic.co/products/kibana
- pek elasticsearch.url i /opt/kibana/config/kibana.yaml til http://172.31.0.18:9200
- start Kibana ved å kjøre /opt/kibana/bin/kibana og se at den klare å kontakte elasticsearch

Logstash and elasticsearch on node logger

---

hieradata/common/modules/profile.yaml
hieradata/common/roles/cephmon.yaml
hieradata/common/roles/compute.yaml
hieradata/common/roles/controller.yaml
hieradata/common/roles/dashboard.yaml
hieradata/common/roles/logger.yaml
hieradata/common/roles/master.yaml
hieradata/common/roles/storage.yaml
profile/manifests/base/common.pp

These changes allows for more granulated package management and overriding. Parameters can now be set on a pr package basis.

Package management

---

hieradata/vagrant/roles/dashboard.yaml
profile/files/openstack/horizon/overrides.py
profile/manifests/openstack/dashboard.pp
profile/templates/openstack/horizon/local_settings.erb

Kan lett teste hva som endres overrides med å legge inn:
`profile::openstack::dashboard::manage_overrides: false`
i hieradata/vagrant/role/dashboard.yaml
Default er at denne endringen automatisk kommer inn.

Overrides in horizon

---

Puppetfile

Forgot this commit in the previous PR.

Add cumulus licensing module

---

hieradata/common/modules/rabbitmq.yaml
hieradata/vagrant/common.yaml

Fixes for newer rabbitmg (allow default user connecting outside of

---

hieradata/common/roles/master.yaml
profile/manifests/openstack/image.pp
profile/manifests/openstack/image/notify.pp

Added option for glance notification and made registry optional and default false. Hieradata updated to match current setup.

Updated profile setup for image services

---

hieradata/common/roles/volume.yaml
hieradata/nodes/vagrant/vagrant-volume-01.yaml

Enables separation of the cinder service.

Cinder node

---

Puppetfile
hieradata/common/modules/foreman.yaml
hieradata/common/modules/postgresql.yaml
profile/manifests/database/postgresql.pp

Upgrade foreman and postgresql puppet modules

Foreman puppet update

---

hieradata/common/common.yaml
hieradata/common/modules/dnsmasq.yaml
hieradata/common/modules/elasticsearch.yaml
hieradata/common/modules/foreman.yaml
hieradata/common/modules/foreman_proxy.yaml
hieradata/common/modules/logstash.yaml
hieradata/common/modules/openstack_extras.yaml
hieradata/common/modules/profile.yaml
hieradata/common/roles/access.yaml
hieradata/common/roles/admin.yaml
hieradata/common/roles/cephmon.yaml
hieradata/common/roles/compute.yaml
hieradata/common/roles/console.yaml
hieradata/common/roles/dashboard.yaml
hieradata/common/roles/identity.yaml
hieradata/common/roles/image.yaml
hieradata/common/roles/logger.yaml
hieradata/common/roles/login.yaml
hieradata/common/roles/master.yaml
hieradata/common/roles/network.yaml
hieradata/common/roles/novactrl.yaml
hieradata/common/roles/storage.yaml
hieradata/common/roles/volume.yaml
profile/manifests/base/common.pp
profile/manifests/base/physical.pp
profile/manifests/base/yumrepo.pp
profile/manifests/openstack/identity.pp

All yum repos except scl for foreman is now defined in modules/profile.yaml, but most of then is not present. We add then in each role.

Yumrepo update

---

hieradata/common/modules/openstack_extras.yaml
hieradata/common/modules/profile.yaml

This will only make changes to freshly installed hosts. For existing hosts we will need to manually remove yum-priorities package and edit repo-files.

Remove yum priorities

---

hieradata/bgo/roles/controller.yaml
hieradata/common/roles/controller.yaml
hieradata/local1/roles/controller.yaml
hieradata/local2/roles/controller.yaml
hieradata/local3/roles/controller.yaml
hieradata/osl/roles/controller.yaml
hieradata/test01/roles/controller.yaml
hieradata/test02/roles/controller.yaml

These changes cleans up our hieradata and should not make any changes on the controllers themselves.

Clean up double negations from legacy code

---

hieradata/common/roles/db.yaml
profile/manifests/monitoring/sensu/agent.pp
profile/manifests/monitoring/sensu/mysql.pp
profile/templates/monitoring/sensu/mysql.ini.erb

Also use hiera_hash to merge sensu plugins and checks.

Added senus metric and checks to mariadb. Default turned off

---

Puppetfile
hieradata/common/modules/ceph.yaml
hieradata/common/modules/profile.yaml
hieradata/common/roles/cephmon.yaml
hieradata/common/roles/compute.yaml
hieradata/common/roles/image.yaml
hieradata/common/roles/storage.yaml
hieradata/common/roles/volume.yaml
profile/manifests/storage/cephosd.pp

This code is necessary for upgradring ceph from hammer to jewel.
WARNING - deploying this code will break existing installations unless some upgrade steps are performed.

Ceph jewel

---

hieradata/common/modules/cinder.yaml
hieradata/common/modules/keystone.yaml
hieradata/common/modules/profile.yaml
profile/manifests/logging/rsyslog/client.pp
profile/manifests/openstack/network/controller.pp

Changes to make it possible to run more roles on a single node and make management services like syslog optional.

Minor updates for minimal vagrant setup

---

hieradata/common/modules/glance.yaml
hieradata/common/roles/identity.yaml
hieradata/common/roles/image.yaml
profile/manifests/openstack/image.pp

Added option to set glance policy and added new role superuser. Superuser can also upload public images in assigned project.

Public image

---

hieradata/nodes/osl/osl-leaf-01.yaml
hieradata/nodes/osl/osl-leaf-02.yaml
hieradata/osl/modules/calico.yaml

Temporary fix for moving uplink to leaf-02

Osl nettverk

---

Rakefile

fix puppet-lint

---

Puppetfile
hieradata/common/roles/access.yaml
hieradata/common/roles/api.yaml
profile/manifests/application/access.pp
profile/manifests/firewall/pre.pp
profile/manifests/firewall/rule.pp
profile/manifests/openstack/dashboard.pp
profile/manifests/openstack/resource/createnetworks.pp
profile/manifests/openstack/resource/host_aggregate.pp
provision/foreman-settings.sh

Oppdatert firewall modulen fra 1.5 til 1.8. Har også gjort noen mindre endringer for å unngå feil i rekkefølgen puppet utfører oppgavene på. Har kjørt det i noen dager i test i local1 og alt fungerer tilsynelatende ok. Krever nok litt mer testing enten i test02 eller vagrant.

Firewall upgrade

---

hieradata/dev/roles/nat.yaml
hieradata/nodes/dev/dev-nat-01.yaml
nodes.yaml
provision/puppetbootstrap.sh
provision/puppetmodules.sh
provision/puppetrun.sh

Should be non destructive changes. To test, checkout branch and vagrant up nat and whatever linux node using HIMLAR_NODESET=full

Add FreeBSD NAT node for vagrant

---

hieradata/nodes/uib/uib-ha-01.yaml
hieradata/nodes/uib/uib-ha-02.yaml
hieradata/uib/common.yaml

We need an external location for load balancers.

UiB location

---

Puppetfile
hieradata/common/modules/profile.yaml

Se beskrivelse av stegene for oppdatering her:
https://trello.com/c/5nlU8obZ/916-oppdatere-foreman-til-version-114-via-113

Upgrade to Foreman 1.14

---

Puppetfile
hieradata/common/modules/corosync.yaml
hieradata/common/roles/ha.yaml
hieradata/dev/modules/corosync.yaml
hieradata/dev/roles/ha.yaml
hieradata/nodes/dev/dev-ha-01.yaml
hieradata/nodes/dev/dev-ha-02.yaml
hieradata/uib/common.yaml
hieradata/uib/roles/ha.yaml
profile/manifests/firewall/rules.pp
profile/manifests/highavailability/corosync.pp
profile/manifests/highavailability/loadbalancing/haproxy.pp
provision/corosync/authkey

Role ha with corosync and haproxy.

New role ha

---

hieradata/common/modules/mysql.yaml
hieradata/nodes/bgo/bgo-db-01.yaml
hieradata/nodes/osl/osl-db-01.yaml
profile/manifests/database/galera.pp
profile/manifests/database/mariadb.pp

Updates cluster name and firewall rules

Galera update

---

Puppetfile
hieradata/common/modules/keystone.yaml
hieradata/common/modules/openstack_extras.yaml
hieradata/common/roles/identity.yaml
hieradata/dev/modules/keystone.yaml
hieradata/local1/modules/keystone.yaml
hieradata/local2/modules/keystone.yaml
profile/manifests/openstack/identity.pp
provision/patchs/keystone-federation-group-mapping.diff

Deployed in local1, local2, test01 and test02 for testing.

Upgrade identity to newton

---

Puppetfile
hieradata/common/modules/glance.yaml
hieradata/common/roles/image.yaml

These changes upgrades glance to newton release.
To test:
- Check out code and branch
- Update puppet modules on admin node
- Run puppet on image node

Upgrade glance to newton

---

hieradata/nodes/test01/test01-storage-01.yaml
hieradata/nodes/test01/test01-storage-02.yaml
hieradata/nodes/test01/test01-storage-04.yaml
hieradata/nodes/test01/test01-storage-05.yaml
hieradata/test01/roles/storage.yaml

Changes are already implemented in test01 location.

Replace ceph cluster in test01

---

hieradata/common/modules/graphite.yaml
hieradata/common/roles/monitor.yaml
profile/manifests/monitoring/sensu/server.pp

Is the monitor_logrotate:path correct?

logrotate for monitor

---

hieradata/common/modules/horizon.yaml
hieradata/common/roles/dashboard.yaml
hieradata/common/roles/db.yaml
hieradata/local1/common.yaml
hieradata/local1/modules/horizon.yaml
hieradata/local2/common.yaml
hieradata/nodes/bgo/bgo-db-01.yaml
hieradata/nodes/local1/local1-db-01.yaml
hieradata/nodes/local2/local2-db-01.yaml
hieradata/nodes/osl/osl-db-01.yaml
hieradata/nodes/test01/test01-db-01.yaml
hieradata/nodes/test02/test02-db-01.yaml
hieradata/vagrant/common.yaml
profile/manifests/openstack/dashboard.pp
profile/manifests/openstack/database/sql.pp
profile/templates/openstack/horizon/local_settings.erb

Use db to store django session and memcached to speed it up.

Session fix

---

hieradata/common/modules/ceilometer.yaml
hieradata/common/modules/cinder.yaml
hieradata/common/modules/glance.yaml
hieradata/common/modules/keystone.yaml
hieradata/common/modules/nova.yaml
hieradata/common/roles/identity.yaml
hieradata/common/roles/image.yaml
hieradata/common/roles/telemetry.yaml
hieradata/common/roles/volume.yaml
hieradata/test02/modules/ceilometer.yaml
hieradata/test02/modules/cinder.yaml
hieradata/test02/modules/glance.yaml
hieradata/test02/modules/keystone.yaml
hieradata/test02/modules/nova.yaml
hieradata/test02/roles/identity.yaml
hieradata/test02/roles/image.yaml
hieradata/test02/roles/telemetry.yaml
hieradata/test02/roles/volume.yaml
hieradata/vagrant/modules/ceilometer.yaml
hieradata/vagrant/modules/cinder.yaml
hieradata/vagrant/modules/glance.yaml
hieradata/vagrant/modules/keystone.yaml
hieradata/vagrant/modules/nova.yaml
hieradata/vagrant/roles/image.yaml
hieradata/vagrant/roles/telemetry.yaml
hieradata/vagrant/roles/volume.yaml

Litt usikker på profile::monitoring::grafana::datasource: som ligger i vagrant|test02/roles/monitor.yaml, så den er foreløpig utelatt.

Enable more metrics

---

hieradata/bgo/roles/api.yaml
hieradata/bgo/roles/dashboard.yaml
hieradata/common/roles/api.yaml
hieradata/osl/roles/api.yaml
hieradata/osl/roles/dashboard.yaml
profile/manifests/highavailability/loadbalancing/haproxy.pp
profile/manifests/openstack/dashboard.pp

**NB!** Vil at flere reviewer denne før vi merger den på mandag 26. mars etter morgenmøte.
Denne endringer skrur på selinux og fjerner src i brannmuren mot dashboard og api (minux http/https).

Allow from world

---

Puppetfile
hieradata/common/roles/builder.yaml

Remember to restart the puppetmaster on admin

updated modules

---

hieradata/test02/roles/builder.yaml

Removed the public network which caused problems with building images

imagebuilder on test02

---

hieradata/common/modules/keystone.yaml
hieradata/common/roles/identity.yaml
hieradata/local1/common.yaml
hieradata/local2/common.yaml
hieradata/local3/common.yaml
hieradata/vagrant/common.yaml

Added a new admin_view role and and user for access with admin_view

admin_view role

---

Puppetfile
hieradata/common/modules/dpapp.yaml
hieradata/common/roles/access.yaml
hieradata/common/roles/mq.yaml
hieradata/local1/common.yaml
hieradata/local2/common.yaml
hieradata/local3/common.yaml
hieradata/vagrant/common.yaml
hieradata/vagrant/modules/dpapp.yaml

Legger til nye felt i production.ini på access (via dpapp modulen) og setter opp en egen mq bruker for access. Legger også inn openstack cli på access slik at vi kan teste access brukeren (admin_view skal kun gi tilgang til user list og user show!).

Access update

---

Puppetfile
hieradata/bgo/modules/etcd.yaml
hieradata/common/modules/etcd.yaml
hieradata/common/modules/profile.yaml
hieradata/common/roles/compute.yaml
hieradata/common/roles/network.yaml
hieradata/osl/modules/etcd.yaml
hieradata/test01/modules/etcd.yaml
hieradata/test02/modules/etcd.yaml
profile/manifests/openstack/network/calico.pp
profile/templates/network/etcd_grpc_proxy_service.erb

Do not merge until ready for upgrading.

Upgrade calico 2.6.x to 3.1.x

---

hieradata/common/modules/nova.yaml
hieradata/common/roles/mq.yaml
hieradata/local1/common.yaml
hieradata/local2/common.yaml
hieradata/local3/common.yaml
hieradata/vagrant/common.yaml

Må samkjøres med commit i secrets repo.

s/nova::rabbit_password/nova_rabbit_password/

---

hieradata/common/modules/nova.yaml
hieradata/vagrant/modules/nova.yaml
profile/manifests/openstack/novactrl.pp

nova-api wsgi

---

hieradata/common/modules/dpapp.yaml

Denne må ut etter at vi har byttet pakke til himlar-dp-prep på access-01

Change openstack user from admin to access for dpapp

---

hieradata/common/modules/keystone.yaml
hieradata/common/roles/identity.yaml

This might speed up identity...

Added memcached to keystone on identity

---

hieradata/bgo/roles/novactrl.yaml
hieradata/common/modules/nova.yaml
hieradata/test02/modules/nova.yaml
hieradata/test02/roles/novactrl.yaml
hieradata/vagrant/roles/novactrl.yaml
profile/manifests/openstack/resource/host_aggregate.pp

Denne bør vente til https://trello.com/c/sRrZzZ5t/1488-sette-opp-egen-az-for-windows-p%C3%A5-bgo-compute-0910 er diskutert og evt. justert/forkastet.

Setup aggregate filter and default type

---

hieradata/nodes/test02/test02-access-01.yaml
hieradata/nodes/test02/test02-admin-01.yaml
hieradata/nodes/test02/test02-admin-02.yaml
hieradata/nodes/test02/test02-builder-01.yaml
hieradata/nodes/test02/test02-cephmon-01.yaml
hieradata/nodes/test02/test02-cephmon-02.yaml
hieradata/nodes/test02/test02-cephmon-03.yaml
hieradata/nodes/test02/test02-console-01.yaml
hieradata/nodes/test02/test02-controller-00.yaml
hieradata/nodes/test02/test02-controller-01.yaml
hieradata/nodes/test02/test02-controller-02.yaml
hieradata/nodes/test02/test02-controller-03.yaml
hieradata/nodes/test02/test02-dashboard-01.yaml
hieradata/nodes/test02/test02-dashboard-mgmt-01.yaml
hieradata/nodes/test02/test02-identity-01.yaml
hieradata/nodes/test02/test02-identity-02.yaml
hieradata/nodes/uit/uit-cryptogw-01.yaml

Første patch, får se når det kommer mer...

Use variables in place of hardcoded values in node files, take 1

---

hieradata/bgo/roles/api.yaml
hieradata/common/roles/api.yaml
hieradata/osl/roles/api.yaml
hieradata/test01/roles/api.yaml
hieradata/test02/roles/api.yaml

https://trello.com/c/HDTgXk5k/1672-avgrense-backends-p%C3%A5-api-til-kun-dem-som-er-installert-i-en-lokasjon

Avgrense backends på API til kun dem som er installert i en lokasjon

---

hieradata/common/roles/dashboard.yaml
hieradata/common/roles/db.yaml
profile/manifests/base/systemd.pp
profile/manifests/base/systemd/limits.pp
profile/manifests/openstack/dashboard.pp

This will now work with a generic service and we use this for mariadb and dashboard

Reworked systemd limits

---

profile/lib/facter/detect_intel_x710.rb

a custom fact for intel x710 slot numbers

---

hieradata/bgo/common.yaml
hieradata/bgo/modules/profile.yaml
hieradata/bgo/roles/cephmon-object.yaml
hieradata/bgo/roles/object-ceph.yaml
hieradata/bgo/roles/object.yaml
hieradata/bgo/roles/rgw.yaml
hieradata/nodes/bgo/bgo-leaf-03.yaml
hieradata/nodes/bgo/bgo-leaf-04.yaml

object storage in bgo with ceph

---

hieradata/bgo/roles/rgw.yaml
hieradata/common/common.yaml
hieradata/common/roles/compute.yaml
hieradata/osl/roles/storage.yaml
hieradata/tos/common.yaml

Så vidt jeg kan se er dette alt som trengs.

Cleaning up named_interfaces

---

hieradata/bgo/roles/rgw.yaml
hieradata/common/common.yaml
hieradata/common/roles/compute.yaml
hieradata/osl/roles/storage.yaml
hieradata/tos/common.yaml

Revert "Cleaning up named_interfaces"

---

hieradata/common/roles/cephmon-object.yaml
hieradata/common/roles/object-ceph.yaml
hieradata/common/roles/rgw.yaml

Må testet i local1 før vi kan rulle denne ut. Tentativt onsdag 10.juli

Upgrade ceph object to nautilus

---

hieradata/common/common.yaml
hieradata/common/roles/cephmon.yaml

Denne skal ut når vi oppgrader til rocky og ikke før!

Upgrade ceph to nautilus

---

hieradata/common/modules/profile.yaml
profile/manifests/base/network.pp

Fix for the "out of sync" issue in foreman

Added https_proxy

---

hieradata/bgo/roles/compute-alice.yaml

should be the correct device name

add disk config for new nvme drives

---

hieradata/bgo/roles/api.yaml
hieradata/common/common.yaml
hieradata/common/roles/api.yaml
hieradata/local1/roles/api.yaml
hieradata/local2/roles/api.yaml
hieradata/osl/roles/api.yaml
hieradata/test01/roles/api.yaml
hieradata/test02/roles/api.yaml
hieradata/vagrant/roles/api.yaml

Changed cert vars and added support for dual domains in haproxy

Added new cert vars and updated haproxy setup for dual domain

---

hieradata/common/roles/torack.yaml
profile/files/monitoring/sensu/systemd/override.conf
profile/manifests/monitoring/sensu/agent.pp

This set up sensu-client on torack  (cumulus debian) in the mgmt vrf net and if metric

Sensu network

---

hieradata/common/roles/torack.yaml
profile/manifests/base/cl_limits.pp

Option to increase address space in limits config on Cumulus Linux

---

hieradata/common/roles/cephmon.yaml
profile/files/base/collectd_cephmon.avc

Testet i test02 i forhold til feilmeldingene i audit-log men ikke i forhold til collectd

SELinux rules for collectd on cephmon

---

hiera.yaml
manifests/site.pp

Create a mech for differating config based on distro and major os version

enable platform on os version

---

profile/manifests/application/foreman.pp

Wait until all steps in the foreman class have completed before applying custom resources.

change requirement for creating foreman resources

---

hieradata/bgo/common.yaml
hieradata/bgo/roles/cephmon-c2.yaml
hieradata/bgo/roles/cephmon-object.yaml
hieradata/bgo/roles/object-ceph.yaml
hieradata/bgo/roles/rgw.yaml
hieradata/bgo/roles/storage-dcache.yaml
hieradata/osl/common.yaml
hieradata/osl/roles/cephmds.yaml
hieradata/osl/roles/cephmon.yaml
hieradata/osl/roles/storage.yaml

* deviates: bgo-storage-dcache, osl-numascale, and test01-compute-01

default is now ceph-quincy

---

hieradata/nodes/osl/osl-spine-01.yaml
hieradata/nodes/osl/osl-spine-02.yaml
hieradata/osl/roles/spine.yaml

feat(osl): bgp peering to sikt from spine

---

hieradata/bgo/roles/admin.yaml

feat(bgo): add compute-host

---

hieradata/common/modules/accounts.yaml
hieradata/common/roles/login.yaml

Sei ifra viss eg har glømt noe :)

ssh-pub,info++

---

hieradata/nodes/bgo/bgo-compute-40.yaml

This server is being re-installed and FW is updated with the NIC fix 
```
Installing Network_Firmware_PX3JF_LN64_22.61.10.77
Installed successfully
```

bgo-compute-40.yaml: turn offloading back on

---

hieradata/osl/roles/spine.yaml

enable elastic ip feature for the rail project

---

puppetfiles/victoria.Puppetfile

Puppet modules with highest version compatible with OpenStack Victoria, and with existing documentation

feat: add victoria.Puppetfile

---

hieradata/common/modules/cinder.yaml
hieradata/common/roles/volume.yaml
nodes.yaml
profile/manifests/openstack/volume.pp

run ansible-playbook lib/upgrade/volume.yaml to upgrade

feat: upgrade cinder to Victoria

---

hieradata/common/platform/el9.yaml
hieradata/common/roles/controller.yaml
hieradata/common/roles/storage.yaml
hieradata/nodes/vagrant/vagrant-controller-01.yaml
hieradata/vagrant/roles/controller.yaml
nodes.yaml
profile/manifests/storage/cephclient.pp
profile/manifests/virtualization/libvirt.pp
provision/puppetbootstrap.sh
puppetfiles/controller.Puppetfile

Includes:
* support for el9
* new puppet env for controller (optional to use)
* new network module for el9

feat(vagrant): el9 controller

---

hieradata/bgo/roles/leaf-v2.yaml

reserved 2x100G link for netapp and cern

feat(bgo): 4x25G set on 7 ports (28 hosts)

---

hieradata/common/modules/horizon.yaml
hieradata/common/roles/dashboard.yaml
nodes.yaml

Upgrade horizon to Wallaby

---

hieradata/common/modules/profile.yaml
hieradata/common/roles/dashboard.yaml
profile/manifests/openstack/dashboard.pp

Works in test
Policy in JSON format is deprecated

Horizon policy fix

---

hieradata/bgo/roles/compute.yaml
hieradata/common/roles/api.yaml
hieradata/common/roles/compute.yaml
hieradata/common/roles/controller.yaml
hieradata/common/roles/dashboard.yaml
hieradata/common/roles/db-global.yaml
hieradata/common/roles/mq.yaml
hieradata/common/roles/nat.yaml
hieradata/common/roles/resolver.yaml
hieradata/osl/roles/compute.yaml
hieradata/test01/roles/compute.yaml
hieradata/test02/roles/compute.yaml

Based on comments in config this should be safe.

Cleanup of old el7 params

---

hieradata/bgo/roles/compute-l40s.yaml
hieradata/bgo/roles/compute-vgpu.yaml
hieradata/common/modules/placement.yaml
hieradata/common/roles/compute.yaml
hieradata/common/roles/console.yaml
hieradata/common/roles/novactrl.yaml
hieradata/nodes/bgo/bgo-compute-vgpu-35.yaml
hieradata/nodes/bgo/bgo-compute-vgpu-53.yaml
hieradata/nodes/osl/osl-compute-vgpu-42.yaml
hieradata/osl/roles/compute-l40s.yaml
hieradata/osl/roles/compute-vgpu.yaml
profile/manifests/openstack/compute.pp
profile/manifests/openstack/novactrl.pp

Revert "Yoga/nova"

---

hieradata/bgo/roles/compute-l40s.yaml
hieradata/bgo/roles/compute-vgpu.yaml
hieradata/common/modules/placement.yaml
hieradata/common/roles/compute.yaml
hieradata/common/roles/console.yaml
hieradata/common/roles/novactrl.yaml
hieradata/nodes/bgo/bgo-compute-vgpu-35.yaml
hieradata/nodes/bgo/bgo-compute-vgpu-53.yaml
hieradata/nodes/osl/osl-compute-vgpu-42.yaml
hieradata/osl/roles/compute-l40s.yaml
hieradata/osl/roles/compute-vgpu.yaml
profile/manifests/openstack/compute.pp
profile/manifests/openstack/novactrl.pp

Revert "Revert "Yoga/nova""
