norcams/himlar

- Vagrantfile
- provision/bootstrap.sh
- provision/puppetrun.sh
This moves the scripts for bootstrap and puppetrun out of the
Vagrantfile. It also modifies the rsync path inside the instance
to /opt/himlar which is a better generic location
> Externalizing bootstrap and puppetrun scripts

- Puppetfile
- hieradata/defaults/common.yaml
- hieradata/defaults/login.yaml
- provision/puppetrun.sh
Having a Puppet module named the same as the main project was confusing. Two profile modules ... was also confusing. This change fixes that, we will carry a norcams branch of puppeels instead, with our local changes.
> Removing himlar Puppet module

- Vagrantfile
- provision/bootstrap.sh
Reworked Vagrantfile, we now got two boxes, 'base' and 'netdev'
* 'vagrant up' or 'vagrant up base' -> base
* 'vagrant up netdev' -> netdev
* 'vagrant up base netdev' -> both
First try at adding support for Debian/Cumulus to the provisioning
scripts.
> Add a 'netdev' vagrant box

- hieradata/defaults/common.yaml
- manifests/site.pp
With this, hiera_include will only query for a special set of classes
to include if the runmode fact is set. This enables e.g bootstrap runs
with the same hiera data set as used for the 'full' runs:
FACTER_RUNMODE=bootstrap puppet apply site.pp
This will include all classes specified as classes_bootstrap in Hiera.
> New feature: run modes

- Vagrantfile
- hieradata/defaults/foreman.yaml
- hieradata/vagrant/foreman.yaml
- provision/puppetrun.sh
Needed to run puppet apply on foreman nodes without editing puppet.conf for every puppet run. 
Quick fix for #54.
> Added command line parms for puppet apply

- provision/foreman-bgo-setup.sh
- provision/foreman-osl-setup.sh
- provision/foreman-trd-setup.sh
With this modified kickstart template one can define a parameter "installdevice" (eg sdb). If the parameter is provided, kickstart will wipe all disk drives on the target and install linux to the provided installdevice. A volume group will be created on that device only, creating /boot, swap and a root lv spanning the rest of the device. This is useful on the storage nodes, where OS will be installed to sdm and vg/lvs on the other drives created by puppet.
If the "installdevice" parameter isn't provided, the default partitioning scheme will be used (useful for most VMs)
> New kickstart template allowing the choice of installdevice

- hieradata/common/common.yaml
- hieradata/common/roles/cephmon.yaml
- hieradata/common/roles/compute.yaml
- hieradata/common/roles/controller.yaml
- hieradata/common/roles/foreman.yaml
- hieradata/common/roles/leaf.yaml
- hieradata/common/roles/login.yaml
- hieradata/common/roles/master.yaml
- hieradata/common/roles/storage.yaml
- manifests/site.pp
* Renamed 'classes' hieradata variable to 'include' and changed it
to a runmode-indexed hash. 'default' contains the array of classes
to include in a normal Puppet run
* Reworked site.pp logic to provide output that is easier to follow
when debugging
> Refactor of site.pp

- Puppetfile
- hieradata/common/common.yaml
- hieradata/common/modules/keyboard.yaml
- hieradata/common/modules/profile.yaml
* Wrote a simple module "keyboard" that sets keymap=no in
/etc/vconsole.conf on RHEL 7 family systems
* Moved hostname management to profile::common::base
> Set keymap=no in vconsole.conf

- Puppetfile
- hieradata/common/modules/ipmi.yaml
- hieradata/common/modules/lldp.yaml
- hieradata/common/modules/profile.yaml
This enables ipmi and lldp modules on physical servers. To do
this a new profile feature is added to make it possible to
include classes based on the value of $::is_virtual
> ipmi and lldp support

- Puppetfile
- hieradata/common/modules/keystone.yaml
These commits enables an apache wsgi server in front of keystone. This is the recommended way of running keystone, and the traditional way is deprecated.
ssl is disabled by default (for now)
It can be reactively implemented on existing installations by stopping the openstack-keystone.service and then running puppet.
> Apache keystone

- hieradata/common/common.yaml
- hieradata/common/modules/profile.yaml
- hieradata/common/roles/cephmon.yaml
- hieradata/common/roles/compute.yaml
- hieradata/common/roles/login.yaml
- hieradata/common/roles/storage.yaml
- profile/manifests/base/common.pp
- profile/manifests/base/firewall.pp
Remove firewall config from initial bootstrap run
Facilitates a third runmode called firstboot
> Puppet firstrun

- hieradata/common/modules/horizon.yaml
- hieradata/vagrant/modules/horizon.yaml
This adds a variable to control mulitdomain support for Horizon and
enables it for the vagrant location
> Enable mulitdomain support for Horizon

- hieradata/common/roles/proxy.yaml
- hieradata/osl/roles/proxy.yaml
The DNS and HTTP/HTTPS proxy feature should only be available from the management network.
> Proxy iptables

- hieradata/common/modules/nova.yaml
- hieradata/common/roles/master.yaml
- hieradata/dev01/common.yaml
- profile/manifests/openstack/compute/hypervisor.pp
- profile/manifests/openstack/volume.pp
- profile/manifests/openstack/volume/api.pp
- profile/manifests/storage/cephclient.pp
These changes give an option to choose ceph as backend to cinder. In addition, it facilitates the possibility for multiple cinder backends of the same and/or different type in any combination.
By default, cinder will be configured with only a single backend, a flat, iSCSI-backed lvm store in a loop file on the cinder node.
> Ceph backend for cinder

- hieradata/common/modules/ceph.yaml
- hieradata/common/modules/glance.yaml
- hieradata/common/roles/cephmon.yaml
- hieradata/common/roles/storage.yaml
- hieradata/dev01/common.yaml
- hieradata/dev01/modules/glance.yaml
These changes allows the glance api to be integrated with a rbd backend. If not explicitly defined, a simple file backend will be provided.
> Integrating glance with ceph backend

- profile/manifests/firewall/expand_rule.pp
- profile/manifests/firewall/rule.pp
Should not break any existing rules, but if $source or $destination is an array it will expand them and add one rule for each.
> An atempt to allow mulitple destination and source in firewall rules

- hieradata/common/roles/dashboard.yaml
- profile/manifests/openstack/api.pp
- profile/manifests/openstack/api/proxy.pp
- profile/manifests/openstack/dashboard.pp
Allow for easier management of the api proxy. All vhosts should be the same as before.
> Moved api proxy away from dashboard profile

- hieradata/common/roles/master.yaml
- hieradata/dev01/roles/master.yaml
- profile/manifests/openstack/network/createnetworks.pp
- profile/manifests/openstack/resource/createnetworks.pp
These changes enables the creation (on neutron master) of networks and subnets in OpenStack.
> Create networks in OpenStack

- hieradata/bgo/roles/dashboard.yaml
- hieradata/common/roles/dashboard.yaml
- hieradata/osl/roles/dashboard.yaml
- hieradata/vagrant/modules/keystone.yaml
- hieradata/vagrant/roles/dashboard.yaml
Dette er et hack som vil hindre at oidc vil sette port to ganger i returaddressen som brukes fra Dataporten/Feide Connect. Det skal nå være mulig å komme rett inn i dashboard uten å fikse URL manuelt.
> Set host request header only when refered from access and dataporten

- hieradata/dev01/modules/calico.yaml
- hieradata/dev01/roles/controller.yaml
- hieradata/nodes/dev01-controller-01.yaml
- hieradata/nodes/dev01-controller-02.yaml
- hieradata/nodes/dev01-dashboard-01.yaml
- hieradata/nodes/dev01-dpapp-01.yaml
- profile/manifests/base/network.pp
- profile/templates/bird/bird.conf.erb
- profile/templates/bird/bird6.conf.erb
Necessary changes for implementing l3 routing for kvm. In addition, new releases of puppet-calico and norcams/puppet-libvirt are required for these changes to work.
In short, this creates a calico-like networking environment, although routes and devices must be created manually (or in code).
> Controller routing

- hieradata/common/common.yaml
- hieradata/common/roles/login.yaml
- hieradata/vagrant/common.yaml
Make sure ssh by default is only allowed from mgmt net. Except login and vagrant where access is global.
> Updated firewall rules for ssh

- Puppetfile
- hieradata/common/roles/leaf.yaml
- hieradata/nodes/dev01-leaf-02.yaml
- profile/manifests/base/network.pp
- profile/manifests/network/leaf.pp
- profile/templates/network/cl-interfaces.erb
These changes provides more mechanisms for configuring a Cumulus leaf node:
- sudo config
- network management for switch ports and bridges
- management VRF for eth0
- installation of license file
For this to work, puppet modules must be refreshed (cumulus interface module, cumulus license module, general networking module).
> Cumulus configuration

- nodes.yaml
Add a base nodeset to ease simple testing and expose only the config present in the base profile
> Base nodeset and role

- Puppetfile
- hieradata/common/modules/calico.yaml
- hieradata/common/modules/neutron.yaml
- hieradata/common/modules/profile.yaml
- hieradata/common/roles/compute.yaml
- profile/manifests/openstack/network.pp
These changes upgrades calico to version 1.4. While new installations are fine, upgrading from version 1.3 demands a few manual steps.
On the network node:
1) Update yum repos:
FACTER_RUNMODE=kickstart puppet agent -t
2) Then update
yum update -y
3) remove old config files
rm -rf /etc/neutron/*
4) reinstall packages
yum reinstall -y openstack-neutron openstack-neutron-common openstack-neutron-ml2
5) Run puppet agent
puppet agent -t
Then, on compute nodes:
1) Update yum repos:
FACTER_RUNMODE=kickstart puppet agent -t
2) stop and disable neutron-dhcp-agent and neutron-metadata-api
systemctl stop neutron-dhcp-agent
systemctl disable neutron-dhcp-agent
systemctl stop neutron-metadata-agent
systemctl disable neutron-metadata-agent
3) Then update
yum update -y
4) remove old config files
rm -rf …
> Upgrade from calico 1.3 to calico 1.4

- hieradata/bgo/common.yaml
- hieradata/local1/common.yaml
- hieradata/local3/common.yaml
- hieradata/osl/common.yaml
- hieradata/test01/common.yaml
- hieradata/test02/common.yaml
- profile/manifests/openstack/network/calico.pp
- profile/templates/bird/bird.conf.erb
Bidirectional Forwarding Detection (BFD) in conjunction with BGP enables rapid link failure detection in our L3 routing scheme. While rather useless in our single uplink, single router environment for the time being, it will be very useful once we enable more routers, uplinks.
These changes are non-destructive, i.e. bird will not break if leafs are unconfigured. Only thing needed is the location spesific netcfg_trp_gateway variable. No default is provided by purpose.
BFD is already configured on existing leaf nodes.
> Implement BFD protocol on compute nodes

- profile/manifests/network/leaf.pp
- profile/manifests/network/leaf/acl.pp
- profile/templates/network/cumulus-acls.erb
We need a method for passing ACLs to our cumulus boxes. For this to work properly, we must use the custom cl-acltool in cumulus linux, which ensures that the rules are installed in ASIC. These changes adds the ability to create rule files and update the running ACLs.
> Add ability to create cumulus acl files

- Puppetfile
These updates are necessary for foreman 1.13 to work. They work with foreman 1.12.
> Update the foreman puppet modules

- hieradata/common/roles/compute.yaml
- profile/manifests/openstack/compute/hypervisor.pp
Move snapshot temp save location to the instance disk. These changes will forcefully move the location, so any snapshot being taken at puppet run time will fail. Implement with caution and coordinate puppet runs on the hypervisors accordingly.
> Change snapshot save location

- hieradata/common/modules/nova.yaml
- hieradata/common/roles/compute.yaml
- hieradata/common/roles/novactrl.yaml
- hieradata/dev/modules/nova.yaml
- profile/manifests/openstack/compute.pp
- profile/manifests/openstack/novactrl.pp
- profile/manifests/openstack/resource/host_aggregate.pp
No host aggregate will be created, and we use the old nova AZ as default. Nothing should change.
> Host aggregate and availability zone

- hieradata/common/modules/ceph.yaml
- hieradata/common/roles/compute.yaml
- hieradata/common/roles/image.yaml
- hieradata/common/roles/storage.yaml
- hieradata/common/roles/volume.yaml
- hieradata/test01/modules/nova.yaml
1) Roles volume, image and compute need only a subset of ceph keys. These changes cleans up a bit, specifying witch keys are distributed where.
2) Implements central ceph storage for location test01
3) Creates a new pool in ceph clusters, "vms", where future instance disks will be located
These changes should be non destructive. To test:
Either delete all keys /etc/ceph/ceph.client.* and run puppet on volume, image and compute, or better:
Reinstall volume and image nodes, and one or more compute nodes.
> Ceph cleanup and preps for instance storage on ceph

- hieradata/common/modules/profile.yaml
- hieradata/common/roles/compute.yaml
- hieradata/common/roles/network.yaml
This upgrade is mostly trivial and applies to network node and computes. To test (already implemented in test01):
1) Delete the old calico repository in /etc/yum.repos.d/
2) Do a FACTER_RUNMODE=kickstart puppet run
3) Clean yum cache with yum clean all
4) Upgrade packages with yum update -y \*calico\*
5a) On network node:
- systemctl restart neutron-server.service
5b) On computes:
- Kill existing dnsmasq processes
- systemctl restart calico-felix.service
- systemctl restart calico-dhcp-agent.service
6) Start instances and observe a new dnsmasq process, route creation and network connectivity for instance
> Upgrade calico plugin from 1.4 to 2.2 for neutron

- profile/templates/logging/logstash/openstack.conf.erb
_Last pull request was merged by mistake and has been reverted. Let's try again._
This isn't very pretty, but will do for now; we're basically dropping any message containing the words nova|glance|neutron|cinder|keystone|horzion|calico|etcd
if type is syslog, which is a little drastic, but keeps us from drowning in duplicates and unnecessary messages.
Also a simple grok pattern for the more inconsistent syslog type.
> Collect and parse /opt/log/*/messages (again)

- Puppetfile
- hieradata/common/modules/neutron.yaml
Default domain needs to be 'default' and not 'Default' for keystone auth to work in neutron
> Updated neutron module and set default domain to lowercase

- hieradata/common/modules/haproxy.yaml
- hieradata/common/modules/rsyslog.yaml
- hieradata/common/roles/api.yaml
- profile/manifests/messaging/rabbitmq.pp
- profile/templates/logging/rsyslog/server.conf.erb
Change use of syslog facitly and use local6 for all custom facilities. Rabbitmq and haproxy now uses local6 and will log to /opt/log/norcams.log on logger-01.
> Syslog update

- Puppetfile
- hieradata/common/modules/cinder.yaml
- hieradata/common/roles/volume.yaml
These changes upgrades glance to newton release.
To test:
- Check out code and branch
- Update puppet modules on admin node
- Remove cinder packages and /etc/cinder
- Run puppet on image node
or run the ansible upgrade job
> Upgrade cinder to newton

- Puppetfile
- hieradata/common/modules/neutron.yaml
- hieradata/common/roles/network.yaml
These changes upgrades neutron to newton release.
To test:
Check out code and branch
Update puppet modules on admin node
Remove neutron packages and /etc/neutron
Run puppet on network node
or better, run the ansible upgrade job
> Upgrade neutron to newton release

- Puppetfile
- hieradata/common/modules/nova.yaml
- hieradata/common/roles/compute.yaml
- hieradata/common/roles/novactrl.yaml
- hieradata/nodes/bgo/bgo-db-02.yaml
- hieradata/nodes/local1/local1-db-02.yaml
- hieradata/nodes/local2/local2-db-02.yaml
- hieradata/nodes/osl/osl-db-02.yaml
- hieradata/nodes/test01/test01-db-02.yaml
- hieradata/nodes/test02/test02-db-02.yaml
- profile/manifests/openstack/compute/hypervisor.pp
- profile/manifests/openstack/database/sql.pp
These changes upgrades nova to newton release, including compute. To test:
- Stop puppet on all nodes for good measure
- Deploy code, delete nova puppet module, update modules
On node identity:
- run puppet
- delete all novav3 endpoints
On node db-02:
- run puppet
- run puppet again
On node novactrl:
- stop openstack services (api, conductor, consoleauth, scheduler)
- do a facter=kickstart puppet run 
- yum update -y
- uninstall openstack-nova-common and openstack-nova-api
- rm -rf /etc/nova/
- rm -rf /var/lib/puppet/lib
- run puppet
- run puppet again
Later, on computes:
- stop openstack services
- do a facter=kickstart puppet run
- yum update -y
- uninstall openstack-nova-common and openstack-nova-api
- rm -rf /etc/nova/
- rm -rf /var/lib/puppet/lib
- run puppet
- run puppet again …
> Upgrade nova from mitaka to newton

- Puppetfile
- hieradata/common/common.yaml
- hieradata/common/modules/gnocchi.yaml
- hieradata/common/modules/profile.yaml
- hieradata/common/roles/api.yaml
- hieradata/common/roles/metric.yaml
- hieradata/dev/roles/metric.yaml
- hieradata/nodes/bgo/bgo-db-01.yaml
- hieradata/nodes/bgo/bgo-db-02.yaml
- hieradata/nodes/osl/osl-db-01.yaml
- hieradata/nodes/osl/osl-db-02.yaml
- hieradata/nodes/test01/test01-db-01.yaml
- hieradata/nodes/test01/test01-db-02.yaml
- hieradata/nodes/test02/test02-db-01.yaml
- hieradata/nodes/test02/test02-db-02.yaml
- hieradata/nodes/vagrant/vagrant-metric-01.yaml
- hieradata/vagrant/common.yaml
- hieradata/vagrant/roles/metric.yaml
- nodes.yaml
- profile/manifests/openstack/database/sql.pp
- profile/manifests/openstack/gnocchi.pp
- profile/manifests/openstack/identity.pp
Dessuten må det til en patch på metric-noden:
```
--- /usr/bin/gnocchi-api        2017-09-19 20:27:43.000000000 +0200
+++ /tmp/gnocchi-api    2017-11-16 09:01:41.692212476 +0100
@@ -16,7 +16,7 @@
description=build_wsgi_app.__doc__,
formatter_class=argparse.ArgumentDefaultsHelpFormatter,
usage='%(prog)s [-h] [--port PORT] -- [passed options]')
-    parser.add_argument('--port', '-p', type=int, default=8000,
+    parser.add_argument('--port', '-p', type=int, default=8041,
help='TCP port to listen on')
parser.add_argument('args',
nargs=argparse.REMAINDER,
```
> Added metric node

- hieradata/nodes/test02/test02-controller-00.yaml
- hieradata/nodes/test02/test02-leaf-01.yaml
- hieradata/nodes/test02/test02-nat-linux-01.yaml
- hieradata/nodes/test02/test02-proxy-01.yaml
- hieradata/test02/common.yaml
- hieradata/test02/roles/compute.yaml
- profile/manifests/network/nat.pp
Statisk IPv6-rute på br2 på test02-controller-00 settes foreløpig manuelt da dette ikke kan fikses via puppet uten patching i ekstern(e) modul(er):
[test02-controller-00 ~]$ cat /etc/sysconfig/network-scripts/route6-br2 
fd34::/64 via fd30::2 dev br2 table main
> Add IPv6 and NAT (for private IPv4) to test02

- hieradata/bgo/modules/nova.yaml
- hieradata/osl/modules/nova.yaml
- hieradata/test01/modules/nova.yaml
We must specify cpu model for the instances in order for live migration to work. For the production sites the haswell generation is the lowest common denominator.
> Specify cpu model for instance migration

- hieradata/common/roles/volume.yaml
- profile/lib/puppet/provider/cinder.rb
- profile/lib/puppet/provider/cinder_type_norcams/openstack.rb
- profile/lib/puppet/type/cinder_type_norcams.rb
- profile/manifests/openstack/volume/api.pp
a) add a new custom cinder volume type which enables us to specify if the type is public or private
b) use the new custom type instead of deprecated type class in cinder puppet module
These changes should not make any changes on existing systems.
> add custom volume type, remove deprecated from cinder

- hieradata/common/modules/profile.yaml
- hieradata/common/roles/identity.yaml
- profile/manifests/openstack/identity.pp
Use mariadb repo to install mariadb client on identity.
Tested on vagrant.
> Identity mariadb

- hieradata/common/roles/api.yaml
Denne løser denne: https://trello.com/c/DtmsXiLo/1392-redirekte-nettskjema-til-uh-iaasno-something
Jeg valgte request.`$domain_frontend` (request.uh-iaas.no i prod) som subdomene, men det kan enkelt endres til noe annet. Når vi er enig kan vi merge og bestille domene hos UNINETT og peke på den mot CNAME `uh-api-front.iaas.uib.no`
> Redirect nettskjema from api

- hieradata/bgo/common.yaml
- hieradata/common/common.yaml
- hieradata/common/roles/api.yaml
- hieradata/osl/common.yaml
- hieradata/test01/common.yaml
- hieradata/test01/roles/api.yaml
- hieradata/vagrant/common.yaml
Will do the following:
* create array for testing network in common
* restrict access to api/haproxy in test01 to only testing network
* add optional access list to use for maintenance based on testing network
> Api restriction

- Puppetfile
Burde være helt uproblematisk. Disse ble også oppgradert til ocata 4-5 mnd før resten.
> Updated puppet module for oslo and openstack lib to pike

- hieradata/common/roles/identity.yaml
- hieradata/vagrant/roles/identity.yaml
Will lock account for 1 hour after 10 failed auth attempts for local api user. Tested in vagrant.
> Added lockout after failed login for api users in keystone

- Puppetfile
- hieradata/common/common.yaml
- hieradata/common/roles/compute.yaml
- hieradata/common/roles/image.yaml
- hieradata/common/roles/volume.yaml
- hieradata/local3/common.yaml
- hieradata/local3/roles/storage.yaml
- hieradata/test01/common.yaml
- hieradata/test01/roles/storage.yaml
- profile/manifests/storage/cephosd.pp
- profile/manifests/storage/create_lvm_osd.pp
These changes includes a new mechanism for creating ceph OSDs in profile code instead of using the openstack ceph module. Changes are only applied for local3 and test01 for now.
> Ceph mimic

- hieradata/common/roles/novactrl.yaml
- profile/manifests/openstack/novactrl.pp
This will should setup cells v2 on new locations (e.g. vagrant) and should not be destructive for existing locations.
> Added cell management to novactrl

- hieradata/bgo/roles/compute.yaml
- hieradata/bgo/roles/controller.yaml
- hieradata/bgo/roles/login.yaml
- hieradata/bgo/roles/storage.yaml
- hieradata/nodes/bgo/bgo-proxy-01.yaml
- hieradata/nodes/osl/osl-proxy-01.yaml
- hieradata/osl/roles/compute.yaml
- hieradata/osl/roles/controller.yaml
- hieradata/osl/roles/login.yaml
- hieradata/osl/roles/storage.yaml
- profile/manifests/base/login.pp
- profile/manifests/base/physical.pp
- profile/templates/monitoring/sensu/redfish_check.sh.erb
These changes enables agentless monitoring via modern baseboard management controllers, which should be vendor neutral.
This is only viable in BGO and OSL locations for now.
- new secrets must be deployed to admin
- routes must be enabled on proxy (ifdown eth0 && ifup eth0)
> Enable redfish for agentless monitoring of physical machines via sensu

- hieradata/bgo/roles/compute.yaml
- hieradata/bgo/roles/storage.yaml
- hieradata/common/common.yaml
- hieradata/common/roles/builder.yaml
- hieradata/common/roles/logger.yaml
- hieradata/common/roles/monitor.yaml
- hieradata/common/roles/object.yaml
- hieradata/osl/roles/compute.yaml
- hieradata/osl/roles/storage.yaml
- hieradata/test01/roles/compute.yaml
- hieradata/test02/roles/compute.yaml
- profile/manifests/base/network.pp
- profile/templates/network/auto-if-bondslave.erb
- profile/templates/network/auto-if-teamslave.erb
- profile/templates/network/auto-if.erb
These changes allows automatic creation of network interface files on nodes given
1) Platform is RedHat family
2) an A DNS record is defined in common for the node
3) network::interfaces_hash is not set (in node file)
Supported types:
1) basic interfaces
2) teams and their slaves
3) bonds and their slaves
4) VLAN tagged interfaces (for all of the above types)
Which interfaces to be configured is determined by the named_interfaces::config. Additionally the interface must be defined in profile::base::network::network_auto_opts in order to be configured (mgmt and trp are always defined if in network_auto_opts). This is to avoid creation of duplicate interface files because the named_interfaces::config allows different logical constructs (trp, live, ceph etc) to be the same physical …
> Automatically create network interfaces files on nodes

- hieradata/common/modules/nova.yaml
- hieradata/common/roles/api.yaml
- hieradata/common/roles/console.yaml
- hieradata/common/roles/monitor.yaml
- hieradata/test01/modules/nova.yaml
- hieradata/test01/roles/console.yaml
Prøver igjen.
Dette bytter ut VNC med Spice, og vil således bruke 6080 i stedet for 6082 som port. Se gjerne til at jeg har fått med meg alt.
> Replace spice with vnc 2

- hieradata/common/modules/ceph.yaml
- hieradata/common/roles/cephmds.yaml
- hieradata/common/roles/cephmon.yaml
- hieradata/common/roles/compute.yaml
- hieradata/common/roles/image.yaml
- hieradata/common/roles/volume.yaml
- hieradata/local2/common.yaml
- hieradata/local3/common.yaml
Testet på følgende måte:
* kjørt puppet på cephmon og storage og ingenting endrer seg som forventet
* slettet alle nøkler i /etc/ceph (pluss bootstrap-osd i /var/lib/ceph) på cephmon og storage. Deretter kjørt puppet og nøkler kom tilbake
* slettet nøkler på volume-01 og image-01 og kjørt puppet og får nøkler tilbake
* ceph status har ikke rapportert nye feil etter deployment
Prøvde så å teste med terraform og ansible, men etter 10 min så kommer instansen opp uten nett. Tipper det ikke er relatert til ceph.
> Updated ceph storage secrets vars

- profile/manifests/application/builder.pp
- profile/manifests/application/builder/jobs.pp
- profile/templates/application/builder/build_script.erb
I stedet for å logge til cronlogg vil alle scriptene skrive en individuell rapport i JSONL (JSON Lines) som lagres til /var/log/imagebuilder/<navn>-report.jsonl. Denne inneholder exitcode fra imagebuilder-pipeline'en (inkl xargs sin), output fra imagebuilder og et sluttresultat som baseres på om hele scriptet har kjørt uten feil eller ikke. En rapport overskrives for hver bygging så den kan overvåkes som en tilstand av Sensu. I tillegg omdirigeres output fra imagebuilder-kommandoen til en datert fil i ren tekst.
Rapporten skrives kun dersom miljøvariabelen IMAGEBUILDER_REPORT har verdien "true", som settes i crontab. Dette er for å ikke ende opp med en brukket rapport om en kjører scriptene manuelt. imagebuilder output i ren tekst skrives alltid (periodisk opprydding av disse filene …
> Self-reporting imagebuilder scripts

- hieradata/nodes/osl/osl-torack-01.yaml
- hieradata/nodes/osl/osl-torack-02.yaml
- Remove static default routes
- Add export/import filters for new uplink peers
- Add export filter for route reflector clients (computes) so that they don't inherit external routes from uplink
- Originate default route
> Reconfigure switches for new uplink

- nodes.yaml
- provision/puppetbootstrap.sh
Looks like puppet fails on all el8 nodes. Set the box for the node in `nodes.yaml` to `norcams/base` for a working el7 node.
`nodes.yaml` might break other nodeset than default.
> added support for el8 in vagrant

- profile/templates/bird/bird.conf.bgo.8.erb
Har testa dette litt for mykje.  Ser ingen problem.
Fjerner 129.177.0.0/16 via 172.18.7.4 frå lhc-private, lhc og private(duh).
> fix(bgo): don't export uib-route from uib-table

- profile/manifests/application/builder.pp
- profile/manifests/application/builder/template.pp
- profile/templates/application/builder/report.sh.erb
- profile/templates/application/builder/template.erb
With this we use the local report api to download the report script. This will enable us to run report api in test and have all locations use their own db for reports. Today everybody is sending reports to production (dev, test and prod).
> feat: custom report script in imagebuilder

- Puppetfile
- hieradata/common/roles/builder.yaml
- hieradata/nodes/test01/test01-builder-01.yaml
- hieradata/nodes/test01/test01-controller-02.yaml
- hieradata/test01/roles/builder.yaml
- profile/manifests/application/builder.pp
- profile/manifests/application/builder/windows_jobs.pp
- profile/manifests/application/windowsimage.pp
- profile/templates/application/builder/build_script.erb
- profile/templates/application/builder/windows_build_script.erb
- profile/templates/application/builder/windows_build_script_wrapper.erb
Using the https://github.com/norcams/packer-windows repository, these changes enables building of windows images with packer and qemu. The builder node is responsible for triggering and serving the images, while the images are build on a controller node.
> Windows image building with packer and qemu

- Puppetfile
- hieradata/bgo/common.yaml
- hieradata/common/roles/spine.yaml
- hieradata/nodes/test01/test01-spine-01.yaml
- hieradata/nodes/test01/test01-spine-02.yaml
- hieradata/osl/common.yaml
- hieradata/test01/common.yaml
- hieradata/test01/roles/compute.yaml
- hieradata/test01/roles/spine.yaml
- hieradata/test02/common.yaml
- profile/templates/bird/bird-nat.conf.8.erb
- profile/templates/bird/bird-resolver.conf.8.erb
- profile/templates/bird/bird-rr-ipv4.erb
- profile/templates/bird/bird-rr-ipv6.erb
- profile/templates/bird/bird.conf.8.erb
- profile/templates/bird/bird.conf.bgo.8.erb
**Overview**
These changes add the ability for selected instances in selected projects to announce IPv4/IPv6 prefixes with a BGP speaker of the user's choice to the NREC infrastructure. Usecases include MetalLB for container clusters and failover-handling haproxy servers.
**How it works**
The NREC Team defines a hash in <location>/roles/spine.yaml that includes a 4 byte AS number, an MD5 password, and one or more IPv4/IPv6 CIDRs that the user's project is allowed to announce. The user instances will do the BGP peering with loopback addresses on spine with the said AS number and MD5 password.
**Effect in the NREC infrastructure**
The BGP connections will be multihop eBGP with hops known already from BGP ("hops" being the compute hosts). This creates what is called recursive routing, and …
> feat:Elastic IP for instances with BGP Anycast

- hieradata/nodes/bgo/bgo-compute-01.yaml
Remove LVM physical volume /dev/sdb from bgo-compute-01, this should solve the absence of vg_ext
> bgo-compute-01: fix LVM vg_ext volume member not found

- hieradata/osl/roles/cephmon.yaml
- hieradata/osl/roles/compute-atlas.yaml
- hieradata/osl/roles/storage.yaml
All physical networking infrastructure is MTU 9000 enabled, and jumbo frames can now be enabled on all physical hosts.
> enable jumbo frames for trp network on remaining phyhosts

- hieradata/bgo/common.yaml
- hieradata/bgo/roles/compute.yaml
- hieradata/bgo/roles/spine.yaml
- hieradata/osl/common.yaml
- hieradata/osl/roles/compute.yaml
- hieradata/osl/roles/spine.yaml
Adds a private IPv4 neutron network, as well as a new public IPv6 network in the BGO and OSL regions. The IPv4 network will be used by instances BGP-peering with the NREC infrastructure in order to use the Elastic IP feature.
> add new neutron networks for elastic ip feature

- hieradata/nodes/bgo/bgo-compute-03.yaml
Remove LVM physical volume /dev/sdb from bgo-compute-03, this should solve the absence of vg_ext
> bgo-compute-03: fix LVM vg_ext volume member not found

- hieradata/nodes/bgo/bgo-compute-02.yaml
Remove LVM physical volume /dev/sdb from bgo-compute-02, this should solve the absence of vg_ext
> bgo-compute-02: fix LVM vg_ext volume member not found

- hieradata/bgo/roles/leaf-v2.yaml
- hieradata/bgo/roles/spine.yaml
- hieradata/test01/roles/spine.yaml
These changes will allow connection from object-ceph nodes (with cluster networking over VLAN 130). While not currently connected to any  of these switches, it will typically be forgotten the day that happens, and these changes add consistancy across the network. The changes will not incur any immediate changes in the infrastructure, a reboot or manual ifup -a is necessary to actually implement the config change.
> allow vlan 130 and avoid future problems

- hieradata/nodes/bgo/bgo-builder-01.yaml
- hieradata/nodes/osl/osl-builder-01.yaml
- hieradata/nodes/test01/test01-builder-01.yaml
- profile/manifests/application/builder/windows_jobs.pp
Cron is rather quirky, but these changes should ensure that the windows distributions are build *only* the second Wednesday each month. In effect it wil run every day with date 8 to 14, but will only execute if it's Wednesday.
> Run windows builds after patch tuesday

- hieradata/common/roles/compute.yaml
Multiple gems now requires newer Ruby version, we need to pin some of them to work with the version we have until our current Sensu is replaced with the new one.
> Update compute.yaml - Fix: Error installing sensu-plugins-http

- Puppetfile
- hieradata/common/modules/haproxy.yaml
- hieradata/uib/roles/ha-grid.yaml
- hieradata/uib/roles/ha-test.yaml
- hieradata/uib/roles/ha.yaml
These changes allow the configuration of haproxy on el8 nodes. The v6.5.0 version of the haproxy module is the last version supporting puppet 6, while still supporting AlmaLinux.
- works for EL7 and EL8
- works with newer puppet clients
- tested for the NREC api role (EL7/EL8)
- tested for the uib/test-ha role (EL7)
- the status page is still working
> EL8 compat changes for HAproxy puppet module

- hieradata/bgo/roles/spine.yaml
- hieradata/common/roles/spine.yaml
- hieradata/osl/roles/spine.yaml
- hieradata/test01/roles/spine.yaml
**ECMP (Equal Cost MulitPath) resilient hashing**
For anycast trafficflows over tcp, resilient hashing offers more determinism when the number of nexthops changes. Read the full details here;
https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-43/Layer-3/Routing/Equal-Cost-Multipath-Load-Sharing-Hardware-ECMP/
These configuration changes will only change the traffic configuration file, and in order for the changes to take effect, **switchd** must be restarted (**not recommended**) or the switch need to be rebooted (**recommended**).
> Enable ECMP resilient hashing for spines

- hieradata/nodes/osl/osl-compute-60.yaml
The server is in placeholder1 and FW is updated with the NIC fix
```
Installing Network_Firmware_PX3JF_LN64_22.61.10.77
Installed successfully
```
> osl-compute-60.yaml: turn offloading back on

- Puppetfile
- Vagrantfile
- hieradata/common/modules/foreman.yaml
- hieradata/common/modules/foreman_proxy.yaml
- hieradata/common/modules/himlar_bootstrap.yaml
- hieradata/common/modules/profile.yaml
- hieradata/common/modules/puppet.yaml
- hieradata/common/roles/access.yaml
- hieradata/common/roles/admin.yaml
- hieradata/common/roles/api.yaml
- hieradata/common/roles/report.yaml
- hieradata/local1/modules/foreman.yaml
- hieradata/local1/modules/himlar_bootstrap.yaml
- hieradata/local1/roles/login.yaml
- hieradata/nodes/local1/local1-login-01.yaml
- hieradata/nodes/osl/osl-controller-08.yaml
- hieradata/osl/modules/himlar_bootstrap.yaml
- hieradata/osl/roles/controller.yaml
- hieradata/test01/modules/himlar_bootstrap.yaml
- hieradata/test01/roles/report.yaml
- hieradata/vagrant/modules/foreman.yaml
- manifests/site.pp
- nodes.yaml
- profile/manifests/application/foreman.pp
- profile/manifests/base/package.pp
- provision/puppetbootstrap.sh
- provision/puppetmodules.sh
- provision/puppetrun.sh
- puppetfiles/admin.Puppetfile
- puppetfiles/ussuri.Puppetfile
This will contain a multitude of upgrades:
- Two new puppet environment with its own Puppetfile: `admin` and `ussuri`
- Updated provision script for multiple puppet environements
- Upgrade puppet from 6 to 7 (on admin)
- Upgrade the admin role from el7 to el8
- Use Appstream postgresql 12 for foreman
- Upgrade foreman to 3.8
- Upgrade all foreman puppet modules to new version
- Upgrade ssh, apache and redis puppet module
In addition we will use ansible to configure foreman and drop use for `provision/foreman_setttings.sh`.
* https://github.com/norcams/himlarcli/pull/123
* https://github.com/norcams/ansible/pull/27
https://github.com/norcams/foreman-setup
https://github.com/norcams/ansible-foreman
> feat: upgrade of admin and foreman

- hieradata/common/common.yaml
- hieradata/common/modules/profile.yaml
- hieradata/common/platform/el8.yaml
These changes syncs the himlar codebase to existing reality: there are no nodes with calico deployed which are on the the el7 platform, and 3.22 is the existing version for all deployments.
When these changes are merged, there will be no calico compatibility for el7, and 3.12/3.20 repos can be deleted from the download server.
> Cleanup of old calico versions - prepare for calico 3.27

- profile/manifests/base/physical.pp
- profile/templates/base/physical/lldpd_interface_conf.erb
The lldpd daemon tries to monitor the tap interfaces created by calico, as well as overlay interfaces like team and bond interfaces. This is nonsensical, and creates unnecessary logging. These changes will create an exclude configuration and restart the lldpd daemon.
> Configure interface exclusion for lldpd

- hieradata/common/common.yaml
- hieradata/common/roles/network.yaml
In order for the API upgrades to succeed, we need to upgrade the calico network plugin as well. Because of a bug in the calico-felix 3.27 RPM package we need to install 3.26 on the compute hosts for now, but the network nodes can be upgraded to 3.26.
There are updated playbooks for the upgrade tasks. Upgrade steps:
1. deploy himlar to admin hosts
2. run upgrade playbook on the network nodes:
`sudo ansible-playbook -e "myhosts=test01-network" lib/upgrade/calico-network.yaml`
3. run upgrade playbook on the compute hosts:
`sudo ansible-playbook -e "myhosts=test01-compute" lib/upgrade/calico-compute.yaml`
4. clear all etcd data:
`sudo ansible-playbook -e "myhosts=test01-network clear_etcd_data=true" lib/upgrade/calico-network.yaml`
The clear_etcd_data variable does what could be expected, and …
> Upgrade calico network plugin to 3.26/3.27

- hieradata/bgo/common.yaml
- hieradata/bgo/roles/rgw.yaml
- hieradata/bgo/roles/spine.yaml
- hieradata/common/roles/api.yaml
- hieradata/common/roles/rgw.yaml
- hieradata/nodes/bgo/bgo-rgw-01.yaml
- hieradata/nodes/bgo/bgo-rgw-02.yaml
- hieradata/nodes/bgo/bgo-rgw-03.yaml
- hieradata/nodes/osl/osl-rgw-01.yaml
- hieradata/nodes/osl/osl-rgw-02.yaml
- hieradata/nodes/osl/osl-rgw-03.yaml
- hieradata/osl/common.yaml
- hieradata/osl/roles/rgw.yaml
- hieradata/osl/roles/spine.yaml
- profile/manifests/highavailability/loadbalancing/haproxy.pp
- profile/templates/bird/bird-rgw.conf.8.erb
- profile/templates/loadbalancing/haproxy_check.erb
These changes enable the ability to disaggregate the object (rgw) gateways from the API frontend used today. In addition, the object service can be served over IPv6 and port 443.
There are several benefits to implement these changes:
**Load balancing**: The anycast feature ensures horizontal scaling of traffic across every RGW node
**High Availability**: Quick convergence if an RGW node fails or goes down for maintenance
**Less service disruption**: The object service will continue to work when the NREC APIs are down for maintenance
**IPv6**: Public facing services should ensure IPv6 compliance
**Implications** : The changes can be implemented without service disruption, as the RGW backends will continue to serve the existing API frontend. When changes are implemented, the DNS record for …
> Disaggregation of NREC APIs and object storage; Anycast haproxy frontends for rgw role with IPv6

- hieradata/bgo/common.yaml
- hieradata/osl/common.yaml
Move the object service endpoint to the now anycast enabled rgw nodes and enable service for IPv6. The transition away from the api node should not cause any service disruption.
> Move object dns pointers to new anycast servers and enable ipv6

- hieradata/vagrant/common.yaml
- hieradata/vagrant/roles/compute.yaml
- hieradata/vagrant/roles/identity.yaml
- hieradata/vagrant/roles/image.yaml
- hieradata/vagrant/roles/network.yaml
- hieradata/vagrant/roles/novactrl.yaml
- hieradata/vagrant/roles/proxy.yaml
- hieradata/vagrant/roles/volume.yaml
- profile/manifests/openstack/compute.pp
- profile/manifests/openstack/identity.pp
- profile/manifests/openstack/image.pp
- profile/manifests/openstack/network.pp
- profile/manifests/openstack/novactrl.pp
- profile/manifests/openstack/volume.pp
Enables OSProfiler for nova, cinder, glance, neutron and keystone with redis collector on proxy
Trace (anywhere):
nova --profile tracethis list --all
openstack --os-profile tracethis server list --all
openstack --os-profile tracethis network list
cinder --profile tracethis list --all
openstack --os-profile tracethis volume list
glance --profile tracethis image-list
openstack --os-profile tracethis image list
View (proxy):
sudo -i
virtualenv osprofiler
source osprofiler/bin/activate
pip install osprofiler graphviz
export OSPROFILER_CONNECTION_STRING=redis://172.31.0.12:6379
osprofiler trace list
osprofiler trace show --html id --out traces/id.html
osprofiler trace show --dot --render-dot traces/id id
> OSProfiler

- hieradata/bgo/common.yaml
- hieradata/bgo/roles/compute.yaml
- hieradata/bgo/roles/image.yaml
- hieradata/common/roles/compute.yaml
- hieradata/common/roles/image.yaml
- hieradata/common/roles/volume.yaml
- hieradata/local3/common.yaml
- hieradata/local3/roles/image.yaml
- hieradata/nodes/bgo/bgo-compute-vgpu-54.yaml
- hieradata/osl/common.yaml
- hieradata/osl/roles/compute.yaml
- hieradata/osl/roles/image.yaml
- hieradata/test01/common.yaml
- hieradata/test01/roles/compute.yaml
- hieradata/test01/roles/image.yaml
- hieradata/test02/common.yaml
- hieradata/test02/roles/image.yaml
- hieradata/tos/common.yaml
- hieradata/vagrant/roles/compute.yaml
- hieradata/vagrant/roles/image.yaml
- hieradata/vagrant/roles/volume.yaml
- profile/manifests/openstack/image.pp
- profile/manifests/openstack/volume.pp
* use profile::storage::cephclient::enable directly in hieradata
* moved setting to hieradata/common/roles/stuff.yaml
* must opt out on non-ceph locations, eg. vagrant
> feat: remove $manage_rbd -> don't use hidden implicit include for profile::storage::cephclient

- hieradata/osl/common.yaml
Changes for osl-spines are already implemented, and announcing from 158.37.66.0/24 works as expected.
> Add new neutron public ipv4 network

- hieradata/nodes/bgo/bgo-compute-vgpu-54.yaml
in /etc/modprobe.d/somefile
sets `options nouveau modeset=0`
> feat: disable nouveau on bgo-compute-vgpu-54

- hieradata/bgo/roles/spine.yaml
- hieradata/osl/roles/spine.yaml
These IPs will serve as endpoint for an internal smtp service in each RAIL cluster.
> Add internal ips for RAIL anycasting

- hieradata/bgo/roles/storage-dcache2.yaml
- hieradata/bgo/roles/volume.yaml
- hieradata/common/modules/ceph.yaml
- hieradata/common/roles/compute.yaml
- hieradata/common/roles/volume.yaml
removes from himlar:
- ceph-pool dcache_hdd_ec_meta8 and dcache_hdd_ec_data8
- cinder volume type: mass-storage-dcache-temp-slow
- cinder user/client key-config
> feat(bgo): remove volume mass-storage-dcache-temp-slow

- hieradata/common/roles/report.yaml
- profile/manifests/application/report.pp
- profile/templates/application/report/scripts/common/request.py
Use template for `common/request.py` fragment to allow use of location specific report utils download links
> feat: add option to use template for report utils script generation

- hieradata/test01/roles/compute.yaml
- profile/manifests/base/common.pp
https://codecave.cc/multipath-routing-in-linux-part-2.html
The default value is 0, which results in layer3 policy, so source/dest addr (+ipv6 flow label), setting it to 1 gives the layer4 policy, which additionally includes source/dest port and the used protocol
> fix: use layer 4 hash policy to distribute load better
